import React from 'react';
import { useVisualizerStore, type VisualizerType } from '../../stores/visualizerStore';
import { cn } from '../../utils/cn';
import { Layers } from 'lucide-react';


export const EffectSelector: React.FC = () => {
    const { addTrack } = useVisualizerStore();

    const renderIcon = (type: VisualizerType, isMirrored: boolean) => {
        const color = "#FF1414";

        if (type === 'bar') {
            if (isMirrored) {
                // Mirrored Bar: Vertically Symmetrical (Waveform style)
                // Center Y = 20. Bars grow up/down from center.
                // Generated by calculating y = 20 - (height / 2)
                return (
                    <svg viewBox="0 0 240 40" className="w-full h-full px-4 py-2" fill={color}>
                        {/* Center Peaks */}
                        <rect x="116" y="5" width="8" height="30" rx="1.5" />

                        <rect x="106" y="8" width="8" height="24" rx="1.5" />
                        <rect x="126" y="8" width="8" height="24" rx="1.5" />

                        {/* Mid Range */}
                        <rect x="96" y="12" width="8" height="16" rx="1.5" />
                        <rect x="136" y="12" width="8" height="16" rx="1.5" />

                        <rect x="86" y="15" width="8" height="10" rx="1.5" />
                        <rect x="146" y="15" width="8" height="10" rx="1.5" />

                        {/* Outer Range */}
                        <rect x="76" y="10" width="8" height="20" rx="1.5" />
                        <rect x="156" y="10" width="8" height="20" rx="1.5" />

                        <rect x="66" y="14" width="8" height="12" rx="1.5" />
                        <rect x="166" y="14" width="8" height="12" rx="1.5" />

                        {/* Edges */}
                        <rect x="56" y="17" width="8" height="6" rx="1.5" />
                        <rect x="176" y="17" width="8" height="6" rx="1.5" />

                        <rect x="46" y="18" width="8" height="4" rx="1.5" />
                        <rect x="186" y="18" width="8" height="4" rx="1.5" />
                    </svg>
                );
            } else {
                // Regular Bar: Simple Frequency style (Bottom Up)
                return (
                    <svg viewBox="0 0 240 40" className="w-full h-full px-4 py-2" fill={color}>
                        <rect x="20" y="25" width="12" height="10" rx="2" />
                        <rect x="38" y="20" width="12" height="15" rx="2" />
                        <rect x="56" y="15" width="12" height="20" rx="2" />
                        <rect x="74" y="28" width="12" height="7" rx="2" />
                        <rect x="92" y="10" width="12" height="25" rx="2" />
                        <rect x="110" y="5" width="12" height="30" rx="2" />
                        <rect x="128" y="12" width="12" height="23" rx="2" />
                        <rect x="146" y="20" width="12" height="15" rx="2" />
                        <rect x="164" y="25" width="12" height="10" rx="2" />
                        <rect x="182" y="18" width="12" height="17" rx="2" />
                        <rect x="200" y="30" width="12" height="5" rx="2" />
                    </svg>
                );
            }
        }

        switch (type) {
            case 'circle':
                return (
                    <svg viewBox="80 0 80 40" className="w-full h-full" fill={color}>
                        <g transform="translate(120, 20)">
                            {[3, 5, 7, 9, 7, 5, 3, 4, 6, 8, 10, 8, 6, 4, 3, 4, 6, 8, 9, 7, 5, 3, 4, 6, 8, 7, 5, 4, 3, 4].map((h, i) => (
                                <rect
                                    key={i}
                                    x="-0.75"
                                    y={-9 - h}
                                    width="1.5"
                                    height={h}
                                    rx="0.75"
                                    transform={`rotate(${i * 12})`}
                                />
                            ))}
                        </g>
                    </svg>
                );
            case 'line':
                return (
                    <svg viewBox="0 0 240 40" className="w-full h-full px-4 py-2" fill="none" stroke={color} strokeWidth="4" strokeLinecap="round">
                        <path d="M20 20 Q 50 5, 80 20 T 140 20 T 200 20" />
                    </svg>
                );
            case 'beat-image':
                return (
                    <div className="w-full h-full flex items-center justify-center opacity-80">
                        <Layers size={24} color={color} />
                    </div>
                );
        }
    };

    const handleSelect = (type: VisualizerType, isMirrored: boolean) => {
        addTrack(type, { mirrored: isMirrored });
    };

    const options: { id: string, type: VisualizerType, isMirrored: boolean, label: string }[] = [
        { id: 'bar-normal', type: 'bar', isMirrored: false, label: 'Bar Wave' },
        { id: 'bar-mirrored', type: 'bar', isMirrored: true, label: 'Mirrored Bar' },
        { id: 'circle', type: 'circle', isMirrored: false, label: 'Circle Wave' },
        { id: 'line', type: 'line', isMirrored: false, label: 'Line Wave' },
        { id: 'beat-image', type: 'beat-image', isMirrored: false, label: 'Beat Image' },
    ];

    return (
        <div className="p-4 space-y-4">


            <div className="flex flex-col gap-2">
                {options.map((opt) => (
                    <button
                        key={opt.id}
                        onClick={() => handleSelect(opt.type, opt.isMirrored)}
                        className={cn(
                            "relative group flex flex-col items-center gap-1 p-2 rounded-xl transition-all border border-transparent overflow-hidden w-full",
                            "hover:bg-white/5 hover:border-white/10 active:scale-95 bg-surface"
                        )}
                    >
                        <div className="h-16 w-full bg-black/40 rounded-lg overflow-hidden flex items-center justify-center">
                            {renderIcon(opt.type, opt.isMirrored)}
                        </div>
                        <span className="text-xs font-medium text-secondary group-hover:text-white transition-colors">
                            {opt.label}
                        </span>
                    </button>
                ))}
            </div>
        </div>
    );
};
